api:
    prefix: /api
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute

index:
    prefix: /
    resource:
        path: ../src/Controller/EntryVue
        namespace: App\Controller\EntryVue
    type: attribute
    requirements:
        route: '^(?!api).*'
