name: Docker Image CI

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: self-hosted
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup environment
                run: ls && chmod u+x .deploy/entrypoints.sh && .deploy/entrypoints.sh
            -   name: Build the Docker image
                run: sudo docker compose build --build-arg ENV=prod
            -   name: Create and start container
                run: sudo docker compose create && sudo docker compose start
